services:
  movienite-api:
    build:
      context: ..
      dockerfile: docker/api.dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: movienite-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
    ports:
      - "23245:23245"
    container_name: movienite-api
    networks:
      - movienite-backend
      - movienite-frontend
    depends_on:
      movienite-db:
        condition: service_healthy


  movienite-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - movienite-db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: movienite-db
    networks:
      - movienite-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  movienite-backend:
    driver: bridge
  movienite-frontend:
    driver: bridge


volumes:
  movienite-db-data:
